# Generated by Django 3.1.5 on 2021-01-31 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture_Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_name', models.CharField(max_length=20)),
                ('start_time', models.TimeField(default=datetime.time(8, 0))),
                ('end_time', models.TimeField(default=datetime.time(10, 0))),
            ],
        ),
        migrations.CreateModel(
            name='Lecture_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departments.dept_courses')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lectures.lecture_duration')),
            ],
        ),
    ]
