# Generated by Django 3.1.5 on 2021-01-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_Stuff', '0001_initial'),
        ('Lectures', '0001_initial'),
        ('Basic_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture_schedule',
            name='stuff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Stuff.stuff'),
        ),
        migrations.AddField(
            model_name='lecture_schedule',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basic_data.academic_year'),
        ),
    ]
