# Generated by Django 3.1.5 on 2021-01-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Student_Stuff', '0001_initial'),
        ('Assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degrees',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student_Stuff.students'),
        ),
    ]
